#define BUTTONS_LISTENER_INTERVAL 50

#define CLEAR_FLOOR_KEYWORD 140
#define REQUEST_COST_KEYWORD 141
#define RECIEVE_COST_KEYWORD 142
#define DELEGATE_ORDER_KEYWORD 143
#define PORT 2456

#define COST_TIMEOUT 2
#define CHECK_FOR_COST_TIMEOUT_INTERVAL 10

#define CHECK_FOR_ORDER_TIMEOUT_INTERVAL 2
#define ORDER_TIMEOUT 5

#define N_FLOORS 4
#define N_BUTTONS 3
#define N_ELEVATORS 3