#define BUTTONS_LISTENER_INTERVAL 50

#define CLEAR_FLOOR_KEYWORD 100
#define REQUEST_COST_KEYWORD 101
#define RECIEVE_COST_KEYWORD 102
#define DELEGATE_ORDER_KEYWORD 103
#define PORT 2456

#define COST_TIMEOUT 0.1
#define CHECK_FOR_COST_TIMEOUT_INTERVAL 20

#define CHECK_FOR_ORDER_TIMEOUT_INTERVAL 2
#define ORDER_TIMEOUT 5

#define OPEN_DOOR_DURATION 3
#define FSM_EVENT_LISTENER_INTERVAL 50

#define N_FLOORS 4
#define N_BUTTONS 3
#define N_ELEVATORS 2